### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by 82018303kazuma** [Tramac/semantic-segmentation-pytorch#1]
python train.py

Traceback (most recent call last):
  File "train.py", line 177, in <module>
    trainer.train()
  File "train.py", line 147, in train
    if not args.Namespace:
AttributeError: 'Namespace' object has no attribute 'Namespace'
&&&&&
pascal_voc.py

from utils import makedirs

cannot import name makedirs

**Comment by Tramac** [comment]
Hi, Thank you for your question.
First, you can try change "from utils import download, makedirs" in pascal_voc.py to "from utils.filesystem import makedirs" and "from from utils.download import download".
I'm sorry for this error because i just push this project and there are some bugs. If you have a QQ, you can cantact me: 1145955920

**Comment by Tramac** [comment]
Hi, I have updated the code, you can try to download again.

**Comment by 82018303kazuma** [comment]
Hi, Thank you for your answer.

I will try to download again.

Thank you.

**Comment by 82018303kazuma** [comment]
python train.py
-------------------------------------------------------------------
Traceback (most recent call last):
File "train.py", line 177, in
trainer.train()
File "train.py", line 147, in train
if not args.Namespace:
AttributeError: 'Namespace' object has no attribute 'Namespace'
-------------------------------------------------------------------
I can run this code（＃if not args.no_eval:） without it, but I'm not sure how to fix this error.

＆＆＆＆

python eval.py
-------------------------------------------------------------------
Testing model:  fcn32s
Finished loading model!
File "eval.py", line 90, in <module>
    eval(args)
  File "eval.py", line 72, in eval
    outputs = model(image)
  File "/home/atsushi/tensorflow/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/atsushi/Pytorch/se/models/fcn.py", line 24, in forward
    pool5 = self.features(x)
  File "/home/atsushi/tensorflow/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/atsushi/tensorflow/local/lib/python2.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/atsushi/tensorflow/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/atsushi/tensorflow/local/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
-------------------------------------------------------------------
I do not know why the size of input and output is not the same.

**Comment by Tramac** [comment]
Hi, have you changed the code "image = image.to(device)"? This error means that input tensor is not on cuda.

**Comment by 82018303kazuma** [comment]
Hi, Thank you for your answer.

What is the version of cuda?

**Comment by Tramac** [comment]
The cuda version in my device is 8.0, but the version of cuda should not be the problem. 
Is the training process over?

**Comment by 82018303kazuma** [comment]
If you erase this code （if not args.Namespace: of train.py), the learning process  over.
then, i obtained weight.

**Comment by Tramac** [comment]
From the error log, the image tensor should be transferred to cuda.
You can try to change the code```outputs = model(image)``` to ```outputs = model(image.cuda())``` if there is CUDA enabled.

**Comment by 82018303kazuma** [comment]
It does not go well.
I try variously.

**Comment by Tramac** [comment]
I'm sorry for these bugs, i will retrain and evaluate these code, please give me some time.
You can continue to post bug logs, i will try my best to help you!

**Comment by Tramac** [comment]
Hi, I have fixed the bug in eval.py, you can try it again. 
I am sorry for my carelessness.

**Comment by 82018303kazuma** [comment]
Thanks for improving the code.
This was better than the code I improved myself.

However, the code here may be different depending on the person.
./weights to ～/.torch/models
./weights to ./torch/models

The overall code is great.
Thank you for the meaningful things.
